# Generated by Django 5.0.2 on 2024-03-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_teacher",
                    models.CharField(
                        max_length=255, verbose_name="Автор/Преподаватель"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("start_date", models.DateField(verbose_name="Дата")),
                ("start_time", models.TimeField(verbose_name="Время")),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
        ),
    ]
