# Generated by Django 5.0.2 on 2024-03-02 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_products_options_remove_products_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="author_teacher",
            field=models.CharField(max_length=255, verbose_name="Автор/Преподаватель"),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.FloatField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="products",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="products",
            name="start_time",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Время начала"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
