# Generated by Django 5.0.2 on 2024-03-02 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_products_author_teacher_alter_products_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_title",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Название урока"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="prod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.products",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.TextField(verbose_name="Ссылка на видео"),
        ),
    ]
