# Generated by Django 5.0.2 on 2024-03-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_lesson_lesson_title_alter_lesson_prod_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Уроки", "verbose_name_plural": "Уроки"},
        ),
    ]
