# Generated by Django 5.0.2 on 2024-03-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_lesson_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.FilePathField(verbose_name="Ссылка на видео"),
        ),
    ]
