# Generated by Django 5.0.2 on 2024-03-02 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_lesson_video_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Группы", "verbose_name_plural": "Группы"},
        ),
        migrations.AlterField(
            model_name="group",
            name="group_title",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Название группы"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="prod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.products",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Имя студента",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(verbose_name="Ссылка на видео"),
        ),
    ]
