# Generated by Django 5.0.2 on 2024-03-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_group_options_alter_group_group_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ("group_title",),
                "verbose_name": "Группы",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("lesson_title",),
                "verbose_name": "Уроки",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("products", models.ManyToManyField(to="courses.products")),
            ],
        ),
        migrations.AlterField(
            model_name="group",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.student",
                verbose_name="Имя студента",
            ),
        ),
    ]
